In [1]:
from sklearn.model_selection import LeaveOneOut
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import accuracy_score 
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df = pd.read_csv('.\heart_data.csv') 
df = df.to_numpy()
X = df[:,1:5]
y = df[:,5]
LDA = LinearDiscriminantAnalysis()
LOOCV = LeaveOneOut()
y_true = []
y_pred = []
for train_index, test_index in LOOCV.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    LDA.fit(X_train, y_train)
    y_true.append(y_test)
    y_pred.append(LDA.predict(X_test))
ac = accuracy_score(y_true, y_pred)
print(ac)
print(LDA.coef_/np.linalg.norm(LDA.coef_))

0.85
[[-0.11013017  0.74571524  0.42921141  0.49755171]]


In [6]:
#2
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X, y)

GaussianNB()

In [7]:
TestA = [[40, 110, 150, 28]] #a
predprobA = model.predict_proba(TestA)
predA = model.predict(TestA)
print(predprobA) 
print("Positive for heart disease:",predA)

[[1.94962046e-05 9.99980504e-01]]
Positive for heart disease: ['Yes']


In [4]:
TestB = [[25, 90,135,26]] #b
predprobB = model.predict_proba(TestB)
predB = model.predict(TestB)
print(predprobB) 
print("Positive for heart disease:",predB)

[[0.12811929 0.87188071]]
Positive for heart disease: ['Yes']


In [5]:
TestC =[[65,90,95,22]] #c
predprobC = model.predict_proba(TestC)
pred = model.predict(TestC)
print(predprobC) 
print("Positive for heart disease:",pred)

[[9.99518400e-01 4.81600145e-04]]
Positive for heart disease: ['No']
