In [10]:
#1
import numpy as np
from scipy.signal import convolve2d

img = np.array([
    [202, 225, 168, 23, 37, 33],
    [251, 114, 63, 66, 32, 56],
    [201, 40, 245, 92, 213, 216],
    [70, 230, 132, 2, 44, 146],
    [8, 218, 171, 10, 193, 48],
    [53, 33, 30, 247, 53, 79]
])  

kernel = np.array([
    [0, -1, 0],
    [-1, 5, -1],
    [0, -1, 0]
])

result = convolve2d(img, kernel, mode='same')
result = np.clip(result, 0, 255)
print(result)


[[255 255 255   0  97  72]
 [255   0   0 120   0   0]
 [255   0 255   0 255 255]
 [  0 255  12   0   0 255]
 [  0 255 255   0 255   0]
 [224   0   0 255   0 255]]


In [15]:
#2a
pool_size = (2, 2)
stride = 2

MaxPool = np.zeros((result.shape[0] // stride, result.shape[1] // stride))

for i in range(0, result.shape[0] - pool_size[0] + 1, stride):
    for j in range(0, result.shape[1] - pool_size[1] + 1, stride):
        MaxPool[i // stride, j // stride] = np.max(result[i:i + pool_size[0], j:j + pool_size[1]])

print(MaxPool)

[[255. 255.  97.]
 [255. 255. 255.]
 [255. 255. 255.]]


In [16]:
#2b

pool_size = (2, 2)
stride = 2

AvgPool = np.zeros((result.shape[0] // stride, result.shape[1] // stride))

for i in range(0, result.shape[0] - pool_size[0] + 1, stride):
    for j in range(0, result.shape[1] - pool_size[1] + 1, stride):
        AvgPool[i // stride, j // stride] = np.mean(result[i:i + pool_size[0], j:j + pool_size[1]]).astype(np.uint8)

print(AvgPool)

[[191.  93.  42.]
 [127.  66. 191.]
 [119. 127. 127.]]
